### ISSUE TITLE
MineSweeper

### ISSUE THREAD

**Issue by L9th** [Byte-Labs-Studio/bl_ui#10]
When you are previewing the mines, you can click on all squares, and when it's time to click on the mines, you can see what squares you've clicked in the previewing.

**Comment by Frowmza** [comment]
is this in last version?, cause i fixed it here https://github.com/Byte-Labs-Studio/bl_ui/commit/5877743547344592f181c878b3831dbf08d5a97b

**Comment by L9th** [comment]
Welp, i thought i downloaded the newest, but I just reinstalled it, and it works! Welp, im just dumb. xd
