### ISSUE TITLE
Trying to implement bl_ui to one of my resources.

### ISSUE THREAD

**Issue by ghost** [Byte-Labs-Studio/bl_ui#4]
Getting this in my F8 console. 

SCRIPT ERROR: @bc_communityservice/client/editable.lua:52: attempt to index a nil value (global 'bl_ui')

the bl_ui is ensured in server.cfg as following

#MINIGAMES
ensure bl_ui

using the 2.0.1version
release bl_ui.zip

**Comment by Frowmza** [comment]
because that is a variable reference of `exports.bl_ui`, so use `exports.bl_ui` instead of `bl_ui`
